### ISSUE TITLE
MinLength is not really minimum

### ISSUE THREAD

**Issue by gberger** [jpotts18/swift-validator#15]
```
    func validate(value: String) -> Bool {
        return countElements(value) > DEFAULT_MIN_LENGTH
    }
````

So if the minimum is 6, and I have 6 characters, it should be valid, but isn't. Only 7 is valid in this example.

The correct should be to use `>=`.

Parallel: the minimum wage is $7.25, so the least you can legally pay someone is $7.25, not $7.26.

**Comment by jpotts18** [comment]
Thanks!
