### ISSUE TITLE
Optional Validation Parameters to be supported

### ISSUE THREAD

**Issue by jpotts18** [jpotts18/swift-validator#5]
Transition to setting values through the constructor instead of through ```Validation.validate(value:String)```

```swift
Required(#message:String)
Password(#regexString:String)
Length(#minLength:Int, #maxLength:Int)
```

**Comment by jkosoy** [comment]
Not sure if this issue would solve it or not, but additionally it would be nice to validate one field against another, such as a "confirm password" field.

**Comment by jpotts18** [comment]
@jkosoy I have been thinking about that, but I am not exactly sure how to best implement it. Any suggestions?
