### ISSUE TITLE
organization

### ISSUE THREAD

**Issue by akume** [jpotts18/swift-validator#6]
I'd like to use it in my project but the validation classes appear to be mixed with a sample project.  I already have a project and am going to have to go through and extract the files that I need so it may be better to put the library in it's own folder and the sample project referencing in another folder so that people can just dump this in their projects.

**Comment by jpotts18** [comment]
Thanks for the suggestion @akume I have updated the repository structure to look like this. 

![screen shot 2015-02-23 at 9 42 51 am](https://cloud.githubusercontent.com/assets/2466729/6332090/8d8ed0d6-bb40-11e4-845b-7d398bc8cb43.png)
