### ISSUE TITLE
MinLengthRule.swift

### ISSUE THREAD

**Issue by ryangilchrist** [jpotts18/swift-validator#8]
Great library and tool.

Small issue inside MinLengthRule.swift:

func validate(value: String) -> Bool {
        if countElements(value) <= DEFAULT_MIN_LENGTH {
            return false
        }
        return true
    }

should be:

func validate(value: String) -> Bool {
        if countElements(value) < DEFAULT_MIN_LENGTH {
            return false
        }
        return true
    }

**Comment by jpotts18** [comment]
I wasn't sure if it should be ``<`` or ``<=`` but I'll make your change until someone else suggests the other way.  Also I have updated my library for Swift 1.2 so ``countElements`` is now ``count``
