### ISSUE TITLE
Error: filename "AppDelegate.swift" used twice

### ISSUE THREAD

**Issue by schan93** [jpotts18/swift-validator#9]
Hi, I am trying to use the Swift Validator but I keep getting an error saying that the AppDelegate.swift is declared twice. What i did was I added the Validator folder and the Validator.xcodeproj to the top level of my application. I would imagine because the compiler sees two declarations of AppDelegate.swift in my project, the compiler cannot see the difference between the two files. As a result, I tried to only include the Validator.xcodeproj into my project and removed the Validator folder from my project but the 'Validator' class is not being recognized. Any ideas on how to fix this?

**Comment by jpotts18** [comment]
An app can only have one AppDelegate.swift. If you put the whole folder in your app it will find two of them and throw an error. You really want to include these files: 

![screen shot 2015-03-27 at 3 01 17 pm](https://cloud.githubusercontent.com/assets/2466729/6876962/2e4c0a1a-d492-11e4-903c-ed3e4be6c7a8.png)

Validator, ValidationRule, ValidationError, Rule, and one of the Rules like EmailRule should show you the pattern. Then you can just pick and choose what you want. I would just add the files into my project manually. I am still trying to figure out how to make a cocoapod in issue #1

**Comment by schan93** [comment]
This is really helpful. Thanks a lot! Really appreciate the clarification.
